### ISSUE TITLE
Consider adding language on schema immutability

### ISSUE THREAD

**Issue by andresuribe87** [w3c/vc-json-schema#120]
The spec requires specifying a version for schemas. I'd like to propose to remove versioning.

Here's how the approach would work:
* Schemas may mutate.
* Mutation to schemas must be backwards compatible (e.g. adding a new field).
* Changes that break backwards compatibility must create a new schema.

The main advantages of a versionless schema spec are:
* Removes the need of a required field.
* No need to do dependency resolution during implementation. (e.g. the question of "is `1.0.3` allowed in the specified `1.0.*` ? ")

There are some disadvantages as well:
* You won't be able to specify things like "All schemas of type x between 0.0.1 and 3.0.1 are allowed". I argue that such a disadvantage isn't that bad, because you can have a new schema for all major revisions. In the previous example, it would be "Accept the following schemas: schema_x_v0, schema_x_v1, schema_x_v2, schema_x_v3".

This is similar to approaches taken with REST apis, where the whole api is versioned, but the request schemas aren't.

Would love to hear thoughts. I admit I'm not clear on what the use cases of versioning look like so far, so feedback is more than welcome.

**Comment by andresuribe87** [comment]
tagging @OR13 for thoughts.

**Comment by OR13** [comment]
Each `credentialSchema` `type` could decide to handle versioning differently.

I agree with many of the comments.

I'm leaning more towards handling versioning in the resource identifier, if it's necessary, not as a metadata property of the schema.

The types defined in this spec are a bit more complicated than I would like.

I prefer simpler processing rules, if possible.

**Comment by decentralgabe** [comment]
Agree and think it should be left as an option in the identifier. I would add spec text pointing to the snowplow schemaver stuff

**Comment by decentralgabe** [comment]
@andresuribe87 please go ahead with a PR to remove most of the versioning text, leaving it as an option in the identifier, and pointing to snowplow's schemaver work.

**Comment by decentralgabe** [comment]
Considering using hashlinks https://w3c-ccg.github.io/hashlink/ cc: @dcrousso

**Comment by decentralgabe** [comment]
Versioning is removed; renaming this issue to reflect the new purpose.

**Comment by OR13** [comment]
I suggest closing the issue, I don't think schemas need to be immutable, and if they do, that should be handled in the identifiers not in JSON-LD.

**Comment by decentralgabe** [comment]
@OR13 this is about adding language to how one would handle it in the identifier

**Comment by OR13** [comment]
I don't think we should add just language.... if you want to use ftp to host your credential schemas, that seems just as valid an IRI as IPFS HTTPS CIDs.

**Comment by decentralgabe** [comment]
I agree with that, it is just as valid

**Comment by decentralgabe** [comment]
Consider just adding text on using https://w3c.github.io/vc-data-model/#integrity-of-related-resources as mentioned https://github.com/w3c/vc-json-schema/issues/172#issuecomment-1627704916
