### ISSUE TITLE
Add language on interop with JSON LD, making use of @vocab

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-json-schema#144]
https://transmute-industries.github.io/vc-json-schema/#jsonschema

```
This [term definition](https://www.w3.org/TR/json-ld/#dfn-term-definition) is https://www.w3.org/ns/credentials/issuer-dependent#JsonSchema.

JsonSchema is used for validation of W3C Verifiable Credentials, based on the latest version of the living standard.

An [issuer](https://www.w3.org/TR/did-core/#identifiers) MAY include a [credentialSchema](https://www.w3.org/TR/vc-data-model/#data-schemas) of [type](https://www.w3.org/TR/json-ld/#specifying-the-type) [JsonSchema](https://transmute-industries.github.io/vc-json-schema/#dfn-jsonschema).
```

**Comment by TallTed** [comment]
It's hard to read a non-wrapping block like that... Here's a wrapped version:

>`This [term definition](https://www.w3.org/TR/json-ld/#dfn-term-definition) is https://www.w3.org/ns/credentials/issuer-dependent#JsonSchema.`
>
>`JsonSchema is used for validation of W3C Verifiable Credentials, based on the latest version of the living standard.`
>
>`An [issuer](https://www.w3.org/TR/did-core/#identifiers) MAY include a [credentialSchema](https://www.w3.org/TR/vc-data-model/#data-schemas) of [type](https://www.w3.org/TR/json-ld/#specifying-the-type) [JsonSchema](https://transmute-industries.github.io/vc-json-schema/#dfn-jsonschema).`
