### ISSUE TITLE
Exact URL-s for the JsonSchema2023 and CredentialSchema2023

### ISSUE THREAD

**Issue by iherman** [w3c/vc-json-schema#154]
At the moment, these terms are defined as

- `https://www.w3.org/ns/credentials/issuer-dependent#JsonSchema2023`
- `https://www.w3.org/ns/credentials/issuer-dependent#CredentialSchema2023`

In my view, that is wrong. The `issuer-dependent` namespace (resulting from the `@vocab` introduced in the VCDM `@context` as a "fall-back") was not meant to express core properties.

This specification is on standard track, and therefore the terms should be placed as terms (to be more precise, RDF Classes, because they are instances of `type` statements) alongside the VCDM terms. This means the correct URL-s should be

- `https://www.w3.org/2018/credentials#JsonSchema2023`
- `https://www.w3.org/2018/credentials#CredentialSchema2023`

And both terms should be properly added to the [VCDM Vocabulary](https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html)

---

To be clear: this issue should not necessary delay the FPWD publication of the spec. This type of change can be done on new versions later.

cc @msporny @dlongley

**Comment by OR13** [comment]
Happy to change the IRIs if the vocabulary is made normative.

There is no point in changing them if it's not, since an implementer will never be required to understand it.

I am also happy to add this stuff to the V2 context, if the context is made normative.
