### ISSUE TITLE
Add note about media types

### ISSUE THREAD

**Issue by OR13** [w3c/vc-json-schema#157]
Based on a slack conversation regarding media types for JSON Schema.

We should recommend:

```
application/schema+json
```

Or

```
application/schema+json; schema="http://json-schema.org/draft-07/schema#
```

When schemas are dereferenced via http (cover both accept and content-type headers).

Related comments:

- https://github.com/orgs/json-schema-org/discussions/198
- https://github.com/ietf-wg-httpapi/mediatypes/blob/main/draft-ietf-httpapi-rest-api-mediatypes.md#json-schema-media-types
- https://json-schema.org/draft/2020-12/json-schema-core.html#name-iana-considerations

**Comment by OR13** [comment]
@decentralgabe I pinged you the related slack thread.

**Comment by decentralgabe** [comment]
this could be relevant https://json-schema.org/draft/2020-12/json-schema-validation.html#section-8.6
cc: @andresuribe87
