### ISSUE TITLE
Example of the credentialSchema.id resolution to schema

### ISSUE THREAD

**Issue by troyronda** [w3c/vc-json-schema#19]
As a followup to #9, it would also be helpful to briefly summarize how the schema document was fetched.

In Example 11, the following is shown:
```
"credentialSchema": {
    "id": "did:work:MDP8AsFhHzhwUvGNuYkX7T;id=06e126d1-fa44-4882-a243-1e326fbe21db;version=1.0",
    "type": "JsonSchemaValidator2018"
  },
```

It would also be helpful to the reader to see how
`did:work:MDP8AsFhHzhwUvGNuYkX7T;id=06e126d1-fa44-4882-a243-1e326fbe21db;version=1.0`
resolved to the schema in Example 10.

**Comment by troyronda** [comment]
(I guess somewhat related to #17).

**Comment by troyronda** [comment]
Also, the link to "Generic DID Parameter Name" is broken in Terminology (https://w3c-ccg.github.io/vc-json-schemas/#terminology)

https://w3c-ccg.github.io/did-core/#generic-did-parameter-names => https://w3c.github.io/did-core/#generic-did-parameter-names

**Comment by glcohen** [comment]
Yes we need to work out a section on **resolution**. My understanding has been that the way you resolve a did document is also the way you resolve a schema. I think we will develop this understanding in #17. 

I will fix the link thanks for pointing it out.

**Comment by decentralgabe** [comment]
Consider adding a section on **resolution** https://www.w3.org/TR/did-core/#resolution, and consider `resolutionMetadata`

**Comment by andresuribe87** [comment]
The original example posted is outdated. The examples in VCDM under [Data Schemas](https://www.w3.org/TR/vc-data-model-2.0/#data-schemas) all have the `id` property set to a URL. So there is no update to do here in the examples. 

Regarding adding a section on resolution, I don't think it's needed for vc-json-schema. The `id` property is already specified in [VCDM](https://www.w3.org/TR/vc-data-model-2.0/#identifiers).

I think this should be closed, unless @decentralgabe had something else in mind.

**Comment by decentralgabe** [comment]
I agree this should be closed, but there's currently an empty section on `resolution` that should be removed with this issue's closure.
