### ISSUE TITLE
JSON schema's `type` and VC.context.JsonSchema.type

### ISSUE THREAD

**Issue by andresuribe87** [w3c/vc-json-schema#194]
Currently, we define `JsonSchema2023` term in https://www.w3.org/ns/credentials/v2 (which will be renamed to `JsonSchema`). That term defines `JsonSchema2023.@context.type == "@type"`. 

Separately, JSON Schema defines `type` in it's meta-schema (downloadable from https://json-schema.org/draft/2020-12/schema). 

I believe this will mean that things break in JSON-LD world when you try to include the full JSON Schema document within the original VC.

**Comment by decentralgabe** [comment]
this is being addressed:
- https://github.com/w3c/vc-data-model/pull/1215
- https://github.com/w3c/vc-data-model/pull/1225
