### ISSUE TITLE
Clarify the usage of the `id` property in `credentialSubject` when using `JsonSchemaCredential`

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-json-schema#197]
Would recommend adding language to say the `id` property should not be present; or if present, match that of the json schema's `$id`.

**Comment by dlongley** [comment]
I'm not sure what "the `id` process" means here -- but we should not have special treatment of `id` in particular cases if that can be avoided.

The VCDM makes a number of elements consistent to ensure it's a modular / compositional data model. This includes consistent treatment of well-known / common elements such as `id` and `type` and the fact that an object in the data model expresses a subject that is identified by the value in `id` and each of its properties are properties of that subject (as identified by `id`).

If a property, such as `jsonSchema` holds some, in effect, "encapsulated value" that has some other rules from that point on in the JSON tree, that's fine -- but it's that property and its definition (and machine readable semantics, i.e., `"type": "@json"` in the context) that makes that clear.

Doing special rules directly in an object in the VCDM that has `id` and `type` without branching off (i.e., appearing at the same level as other things that comply with the standard rules) makes it harder to write generic processors. It's detrimental if people have to find and read a specialized spec to even consume the `id` and `type` values themselves. They should, for example, be able to always treat those elements consistently per the VCDM spec when encountered during traversal of well-known / spec'd properties (such as `credentialSchema`), being able to either ignore or copy / merge "as is" the rest of the object into knowledge graphs even if a particular `type` is not natively understood by the processor.

I'm not quite sure what this issue references, but any solution to it (or whatever underlying problem it's related to) should ensure not to disturb that guarantee. In fact, it would probably be inconsistent with the core VCDM spec and represent a spec bug or general problem if it did disturb that.

**Comment by decentralgabe** [comment]
@dlongley the problem is that it's ambiguous what an id in the credential subject of a JsonSchemaCredential actually means/is used for. To avoid that ambiguity we provide guidance to either give it meaning (as the id of the json schema) or avoid its inclusion altogether

**Comment by TallTed** [comment]
I *think* that ["the `id` process"](https://github.com/w3c/vc-json-schema/issues/197#issue-1843522943) should say "the `id` property", possibly "the `id` property of the `credentialSubject`".

**Comment by decentralgabe** [comment]
see the open PR that addresses this https://github.com/w3c/vc-json-schema/pull/199

**Comment by dlongley** [comment]
@decentralgabe,

> the problem is that it's ambiguous what an id in the credential subject of a JsonSchemaCredential actually means/is used for. To avoid that ambiguity we provide guidance to either give it meaning (as the id of the json schema) or avoid its inclusion altogether

The `id` has the same meaning as it always does in the VCDM, it's an identifier for a subject. It seems that that subject is some kind of json schema container, indicated by the type `JsonSchema`, where the JSON schema itself may appear in the `jsonSchema` property. If people want to use an `id` for that (or omit one) that seems perfectly fine, provided that the `id` follows the same rules as usual (those laid out here: https://www.w3.org/TR/vc-data-model-2.0/#identifiers). That means that using the `id` for something else (the JSON schema itself and not the container) or using an `id` value that is not a URL would not be following those rules.

**Comment by dlongley** [comment]
I think it's important that we say what kind of schema is expressed in each value associated `credentialSchema` and this container / descriptor object does that. Dropping a schema directly into the value wouldn't provide processors with any information about what they are dealing with when they encounter it, leaving them to guess what the thing is. Conflating the schema itself with that descriptor is also a bad idea for this reason. So I think the modeling is appropriate; whether or not an `id` is needed or useful seems to be a separate question.

Using a specific `id` may help someone differentiate one schema from another, for example, if they decide to build something on top of what you've expressed in the VC. For example, maybe someone wants to build a `Map` with keys that are IDs and values that are the descriptors. I could see that being useful for a variety of use cases. So, that's a good reason to have it -- and to use something like a `urn:uuid:<uuid>` for the `id` value, if nothing else.

**Comment by decentralgabe** [comment]
@dlongley please suggest changes here if you disagree with the language https://github.com/w3c/vc-json-schema/pull/199/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R285

I agree with what you've written but I do not see a problem with providing guidance on how a property is used, that's within the bounds of how the VCDM can work.

**Comment by decentralgabe** [comment]
fixed in #199
