### ISSUE TITLE
Add guidance on inclusion of unique tracking identifiers

### ISSUE THREAD

**Issue by andresuribe87** [w3c/vc-json-schema#201]
From https://github.com/w3cping/privacy-request/issues/119

> In section [3.1.1](https://www.w3.org/TR/vc-json-schema/#id) it says that it recommends that the ID property is a dereferenceable IRI. If this IRI is dereferenceable then it could be used to track the usage of the credential when the schema get's dereferenced and the IRI contains a unique identifier in IRI to detect when the schema is being dereferenced to correlate it to an IP address. Further information should be added to this section or to a separate privacy section to deter the inclusion of unique tracking identifiers in the IRIs.

This issue is to track.

**Comment by decentralgabe** [comment]
we have https://github.com/w3c/vc-json-schema/issues/167

**Comment by andresuribe87** [comment]
> we have #167

That's a catch all. I'll add them as separate tasks.
