### ISSUE TITLE
Formalize the jsonSchema property in the VCDM vocabulary?

### ISSUE THREAD

**Issue by iherman** [w3c/vc-json-schema#206]
In my reading the JsonSchemaCredential mechanism relies on, among other things, on a property called `jsonSchema` that must be added to the credential vocabulary. If that is correct, there should be an anchor which can be used from the vocabulary as a formal definition (at the moment, the only thing I saw is a table entry in §2.2. Also, my reading of the text is that the domain of the vocabulary should be `JsonSchema` (that class already exists) and the range should be `rdf:JSON`, meaning that the value is a piece of JSON that is opaque to any JSON-LD processing.

If that is indeed the case, I am happy to create a PR in the VCDM repository with that extension of the vocabulary as soon as I get a stable anchor in the spec that I can rely on.

cc @msporny @andresuribe87 @decentralgabe

**Comment by andresuribe87** [comment]
@iherman I was under the impression that https://github.com/w3c/vc-data-model/pull/1215 was addressing this. Are you saying that we need to make more updates?

**Comment by decentralgabe** [comment]
@andresuribe87 I thought so too..but maybe what @iherman is saying is that while that change addressed the context, it did not address the vocab. So we need another entry [here](https://github.com/w3c/vc-data-model/blob/main/vocab/credentials/v2/vocabulary.yml#L37)?

But I am not sure how to make it not conflict with the existing term

**Comment by iherman** [comment]
@decentralgabe,

> @andresuribe87 I thought so too..but maybe what @iherman is saying is that while that change addressed the context, it did not address the vocab. So we need another entry [here](https://github.com/w3c/vc-data-model/blob/main/vocab/credentials/v2/vocabulary.yml#L37)?

Exactly. Well, not necessary at that line in the file, but the point is that it should be added to the vocabulary.

> 
> But I am not sure how to make it not conflict with the existing term

Let that be my job :-) 

But, if you look at the various terms in that file, there is a pointer back to the specifiation that could be considered as _the_ place where the term is defined. So, for example, the classes the vocabulary refers back to the relevant sections, like https://www.w3.org/TR/vc-json-schema/#jsonschema. However, I would need such a URL that specifically points to the _property_ `jsonSchema` (as opposed to the _class_ `JsonSchema`).

Once I have that, I can take it over.

**Comment by decentralgabe** [comment]
@iherman please review https://github.com/w3c/vc-json-schema/pull/211
