### ISSUE TITLE
[i18n] no need to refer considerations on data serialization defined in the core?

### ISSUE THREAD

**Issue by himorin** [w3c/vc-json-schema#222]
https://www.w3.org/TR/vc-json-schema/#internationalization-considerations

In internationalization considerations section, first sentence notes

>There are a number of internationalization considerations implementers should be aware of when publishing data described in this specification. As with any web standards or protocols implementation, ignoring internationalization makes it difficult for data to be produced and consumed across a disparate set of languages and societies, which would limit the applicability of the specification and significantly diminish its value as a standard. 

which is actually a note for VC-DATA-MODEL but not schema, similar to third sentence

> When using a [verifiable credential](https://www.w3.org/TR/vc-json-schema/#dfn-verifiable-credential) to represent a schema, we recommend following the guidance in the [VC Data Model](https://www.w3.org/TR/vc-data-model-2.0/#internationalization-considerations).

Since this specification defines an integration of JSON Schema into VC-DATA-MODEL, removing first sentence and just keeping thried would be better.

**Comment by iherman** [comment]
@himorin thanks.

Just an admin question: is this the only comment we have to take on board for this document? We are eager to go to CR, and we are waiting for your blessing...

cc @decentralgabe @msporny

**Comment by decentralgabe** [comment]
thanks opened https://github.com/w3c/vc-json-schema/pull/223

**Comment by himorin** [comment]
@iherman I believe so, for the only comment point

**Comment by aphillips** [comment]
Correcting the label but not re-opening
