### ISSUE TITLE
Provide for localization of a VC JSON Schema document

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-json-schema#224]
3.1.3 name, 3.1.4 description
https://www.w3.org/TR/vc-json-schema/#name
https://www.w3.org/TR/vc-json-schema/#description

The `name` and `description` sections linked above say:

> It is RECOMMENDED that all JSON Schemas include a name property which provides a human-readable name that describes the schema. 

> JSON Schemas MAY choose to include an optional description property which provides a human-readable sentence describing the schema. 

While the `name` and `description` fields are defined by JSONSchema, the schemas being defined by users of vc-json-schema are defined by VC. The schemas are used to describe various credential documents. The schema documents thus might need to be localized or need to include language and direction metadata so that users can understand what the credential is supposed to represent.

As a result, there should be notes about including natural language metadata in each of these sections or guidance about how to localize a schema description in the Internationalization Considerations section (or both).

**Comment by decentralgabe** [comment]
thanks @aphillips I will add language to this effect, noting that human readable metadata such as name and description are candidates for localization in json schemas

**Comment by andresuribe87** [comment]
@aphillips thanks for the feedback! I've attempted to fix in #225, by requiring a new field which I named `locale`. It's optional, so when absent it defaults to `en-US`. Is this something that looks good to you?

**Comment by aphillips** [comment]
@andresuribe87's comment above does not convey the actual solution that #225 landed on, but I am **satisified** by the text that was landed.
