### ISSUE TITLE
"enum", "format" in property attributes

### ISSUE THREAD

**Issue by mjfelis** [w3c/vc-json-schema#233]
Hi all, 

I've seen "enum", "format" in property attributes. Where can I find the full list of possible options? I cannot see that in the spec.

BR,

```json
"properties": {
         "credentialSubject": {
           "type": "object",
           "properties": {
             "favoriteColor": {
               "type": "string"
               "enum": ["red", "orange", "green", "blue", "yellow", "purple"]
             }
           },
           "required": ["favoriteColor"]
         }
       }
```

```json
"properties": {
      "credentialSubject": {
        "type": "object",
        "properties": {
          "emailAddress": {
            "type": "string",
            "format": "email"
          }
        },
        "required": ["emailAddress"]
      }
    }
```

**Comment by decentralgabe** [comment]
hi @mjfelis the full set of options are defined by the corresponding json schema spec itself. so, for example, if you're using Draft 2020-12, then you can find the full terms here: https://json-schema.org/draft/2020-12/json-schema-validation#name-a-vocabulary-for-structural

json schema also recently released a nice tour that helps understand all the functionality of the spec https://tour.json-schema.org/

please let me know if you think concrete spec text change would be useful to add clarity here

**Comment by mjfelis** [comment]
Thanks for your feedback. No, I think the spec is clear enough. It's just that I was unaware of json-schemas!

Fabrice
